import os
import re
import datetime
import io
from fpdf import FPDF

class CompliancePDF(FPDF):
    """Custom FPDF class to handle styled headers and footers."""
    def __init__(self, filename: str, doc_type: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.doc_filename = filename
        self.doc_type = doc_type

    def header(self):
        # Top colored accent banner
        self.set_fill_color(31, 58, 86)  # Deep Navy Blue
        self.rect(0, 0, 210, 8, "F")
        
        # Header text
        self.set_y(12)
        self.set_font("helvetica", "B", 8)
        self.set_text_color(120, 120, 120)
        self.cell(100, 5, "SMART DOCUMENT AUDITOR  |  COMPLIANCE TRIAL LEDGER", ln=False, align="L")
        self.set_font("helvetica", "I", 8)
        self.cell(0, 5, f"Source: {self.doc_filename}", ln=True, align="R")
        
        # Divider line
        self.set_draw_color(220, 220, 220)
        self.line(10, 18, 200, 18)
        self.ln(5)

    def footer(self):
        # Bottom divider line
        self.set_draw_color(220, 220, 220)
        self.line(10, 282, 200, 282)
        
        self.set_y(-12)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        
        # Confidentiality indicator (Left)
        self.cell(120, 5, "CONFIDENTIAL  |  Generated by ADK Swarm compliance engine.", ln=False, align="L")
        
        # Page numbering (Right)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", ln=False, align="R")


class PDFReportGenerator:
    """Helper service to compile AuditLog DB records into a beautiful PDF file."""

    @staticmethod
    def generate_report(log_record) -> bytes:
        """
        Builds a styled PDF report in memory from a database log record.

        Args:
            log_record: The AuditLog SQLAlchemy model instance.

        Returns:
            bytes: The raw PDF file bytes.
        """
        filename = log_record.filename
        doc_type = log_record.doc_type or "unknown"
        status = log_record.status or "NON_COMPLIANT"
        severity = log_record.severity or "LOW"
        timestamp = log_record.timestamp or datetime.datetime.utcnow()
        
        # Extract metadata from JSON payload
        full_report = log_record.full_report or {}
        compliance_score = full_report.get("compliance_score", 0)
        pii_detected = full_report.get("pii_was_detected", False)
        audit_result = full_report.get("audit_result", {})
        violations = audit_result.get("violations", [])
        recommendations = audit_result.get("recommendations", [])
        executive_summary = full_report.get("executive_summary", "")

        # ── Initialize PDF Doc ────────────────────────────────────────────────
        pdf = CompliancePDF(filename=filename, doc_type=doc_type, orientation="P", unit="mm", format="A4")
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=20)

        # ── Title Block ───────────────────────────────────────────────────────
        pdf.set_y(22)
        pdf.set_font("helvetica", "B", 22)
        pdf.set_text_color(31, 58, 86)  # Deep Navy Blue
        pdf.cell(0, 10, "Document Audit Report", ln=True)
        
        # Subtitle metadata
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(35, 6, "Audit ID:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.cell(40, 6, f"#{log_record.id}", ln=False)
        
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(35, 6, "Audit Date:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.cell(0, 6, timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"), ln=True)

        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(35, 6, "Document Category:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.cell(40, 6, doc_type.capitalize(), ln=False)
        
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(35, 6, "PII Status:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pii_str = "Redacted / Masked (Safe)" if pii_detected else "No PII Detected"
        pdf.cell(0, 6, pii_str, ln=True)
        pdf.ln(4)

        # ── Dashboard Cards (Verdict, Score, Severity) ───────────────────────
        # Draw a beautiful verdict banner
        y_dashboard = pdf.get_y()
        
        # 1. Verdict Box (Left)
        pdf.set_xy(10, y_dashboard)
        if status.upper() == "COMPLIANT":
            pdf.set_fill_color(223, 240, 216)   # Light Green
            pdf.set_text_color(60, 118, 61)     # Dark Green
            pdf.rect(10, y_dashboard, 60, 24, "F")
            pdf.set_y(y_dashboard + 4)
            pdf.set_font("helvetica", "B", 9)
            pdf.cell(60, 5, "VERDICT STATUS", ln=True, align="C")
            pdf.set_font("helvetica", "B", 13)
            pdf.cell(60, 8, "COMPLIANT", ln=True, align="C")
        else:
            pdf.set_fill_color(242, 222, 222)   # Light Red
            pdf.set_text_color(169, 68, 66)     # Dark Red
            pdf.rect(10, y_dashboard, 60, 24, "F")
            pdf.set_y(y_dashboard + 4)
            pdf.set_font("helvetica", "B", 9)
            pdf.cell(60, 5, "VERDICT STATUS", ln=True, align="C")
            pdf.set_font("helvetica", "B", 13)
            pdf.cell(60, 8, "NON-COMPLIANT", ln=True, align="C")

        # 2. Risk Box (Middle)
        pdf.set_xy(75, y_dashboard)
        # Determine severity colors
        sev_upper = severity.upper()
        if sev_upper == "LOW":
            pdf.set_fill_color(230, 245, 230)
            pdf.set_text_color(40, 130, 40)
        elif sev_upper == "MEDIUM":
            pdf.set_fill_color(252, 248, 227)  # Light yellow
            pdf.set_text_color(138, 109, 59)    # Dark golden
        elif sev_upper == "HIGH":
            pdf.set_fill_color(255, 238, 221)  # Light orange
            pdf.set_text_color(210, 105, 0)     # Dark orange
        else:  # CRITICAL
            pdf.set_fill_color(245, 220, 220)
            pdf.set_text_color(180, 0, 0)
            
        pdf.rect(75, y_dashboard, 60, 24, "F")
        pdf.set_y(y_dashboard + 4)
        pdf.set_x(75)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(60, 5, "RISK SEVERITY", ln=True, align="C")
        pdf.set_x(75)
        pdf.set_font("helvetica", "B", 13)
        pdf.cell(60, 8, sev_upper, ln=True, align="C")

        # 3. Score Box (Right)
        pdf.set_xy(140, y_dashboard)
        pdf.set_fill_color(235, 245, 255)       # Light blue
        pdf.set_text_color(30, 100, 180)        # Dark blue
        pdf.rect(140, y_dashboard, 60, 24, "F")
        pdf.set_y(y_dashboard + 4)
        pdf.set_x(140)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(60, 5, "COMPLIANCE SCORE", ln=True, align="C")
        pdf.set_x(140)
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(60, 8, f"{compliance_score}/100", ln=True, align="C")
        
        # Reset colors and margins
        pdf.set_text_color(0, 0, 0)
        pdf.set_xy(10, y_dashboard + 28)
        pdf.ln(3)

        # ── Executive Summary Section ─────────────────────────────────────────
        pdf.set_font("helvetica", "B", 13)
        pdf.set_text_color(31, 58, 86)
        pdf.cell(0, 6, "Executive Summary", ln=True)
        pdf.ln(1.5)
        
        # Render padded box for the summary
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        
        summary_clean = PDFReportGenerator._clean_markdown(executive_summary)
        
        # Draw a beautiful grey-border container for the summary text
        pdf.set_fill_color(250, 250, 250)
        pdf.set_draw_color(200, 200, 200)
        
        # Render multi-line summary text
        pdf.multi_cell(190, 5.5, summary_clean, border="L", fill=True, align="L")
        pdf.ln(5)

        # ── Key Violations Table (Only if non-compliant/violations exist) ─────
        if violations and status.upper() != "COMPLIANT":
            pdf.set_font("helvetica", "B", 13)
            pdf.set_text_color(169, 68, 66)  # Red tone
            pdf.cell(0, 6, "Detected Compliance Violations", ln=True)
            pdf.ln(2)

            # Table Header
            pdf.set_fill_color(169, 68, 66)  # Red Header
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("helvetica", "B", 9)
            pdf.cell(30, 8, " Violation ID", border=1, ln=False, fill=True)
            pdf.cell(160, 8, " Requirement / Failure Description", border=1, ln=True, fill=True)

            # Table Content Rows
            pdf.set_text_color(40, 40, 40)
            pdf.set_font("helvetica", "", 9)
            
            fill = False
            for idx, violation in enumerate(violations):
                # Clean up rule numbers (e.g. INV-01: text or just text)
                rule_id = "VERIFY"
                desc = violation
                match = re.match(r'^([A-Z]+-\d+):\s*(.*)$', violation)
                if match:
                    rule_id = match.group(1)
                    desc = match.group(2)
                else:
                    rule_id = f"VIOL-{idx+1}"

                # Alternating colored rows
                pdf.set_fill_color(249, 249, 249) if fill else pdf.set_fill_color(255, 255, 255)
                
                # Render ID Cell
                pdf.cell(30, 10, f"  {rule_id}", border="LRB", ln=False, fill=True)
                
                # Render Description Cell
                pdf.multi_cell(160, 5, f" {desc}", border="RB", fill=True)
                
                # Alternate fill color
                fill = not fill
            pdf.ln(5)
        else:
            # Compliant Banner
            pdf.set_font("helvetica", "B", 13)
            pdf.set_text_color(31, 58, 86)
            pdf.cell(0, 6, "Detected Compliance Violations", ln=True)
            pdf.ln(2)
            
            pdf.set_fill_color(240, 248, 240)
            pdf.set_text_color(40, 120, 40)
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(0, 10, "  [OK] No compliance violations detected. Document satisfies all checked rules.", border=1, ln=True, fill=True)
            pdf.ln(5)

        # ── Actionable Recommendations ────────────────────────────────────────
        if recommendations:
            pdf.set_font("helvetica", "B", 13)
            pdf.set_text_color(31, 58, 86)
            pdf.cell(0, 6, "Actionable Recommendations", ln=True)
            pdf.ln(2)

            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            
            for rec in recommendations:
                clean_rec = PDFReportGenerator._clean_markdown(rec)
                
                # Customized bullet point rendering
                pdf.set_text_color(30, 100, 180) # Blue bullet
                pdf.cell(6, 5.5, "->", ln=False)
                pdf.set_text_color(50, 50, 50)  # Reset to dark text
                pdf.multi_cell(184, 5.5, clean_rec)
            pdf.ln(5)

        # ── Rules Reference Block ─────────────────────────────────────────────
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, "Regulatory Standards Applied", ln=True)
        pdf.set_font("helvetica", "I", 8)
        pdf.set_text_color(130, 130, 130)
        pdf.multi_cell(0, 4, f"Evaluation was performed by the Auditor Agent calling the FastMCP Rules Server. Rules applied are sourced from the dynamic rule catalog (Source: {audit_result.get('rule_source', 'MCP Rules catalog')}).")

        # ── Generate Output Bytes ─────────────────────────────────────────────
        # In fpdf2, output(dest='S') or output() returns a bytearray or bytes. 
        # By default in fpdf2, calling output() with no arguments returns a bytearray/bytes or writes to a file depending on format.
        # To get the bytes representation, we can call:
        return bytes(pdf.output())

    @staticmethod
    def _clean_markdown(text: str) -> str:
        """Helper to strip Markdown tags and emojis for raw PDF rendering compatibility."""
        if not text:
            return ""
        
        # 1. Standard markdown syntax stripping
        text = re.sub(r'#+\s*', '', text)  # Headings
        text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)  # Bold
        text = re.sub(r'\*([^*]+)\*', r'\1', text)  # Italics
        text = text.replace("`", "")  # Inline code
        
        # 2. Map common high-unicode punctuation and emojis to ASCII equivalents
        replacements = {
            '\u201c': '"',  # Left double quotation mark
            '\u201d': '"',  # Right double quotation mark
            '\u2018': "'",  # Left single quotation mark
            '\u2019': "'",  # Right single quotation mark
            '\u2013': '-',  # En dash
            '\u2014': '-',  # Em dash
            '\u2022': '*',  # Bullet point
            '\u2705': '[OK]',   # Green checkmark box emoji
            '\u274c': '[FAIL]', # Red X emoji
            '\u26a0': '[WARN]', # Warning sign emoji
            '\U0001f6a8': '[ALERT]', # Police car revolving light
            '\u2714': '[OK]',
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
            
        # 3. Strip all remaining characters outside the Latin-1 range (ord <= 255)
        # This safely filters out remaining emojis (which cause FPDF_UnicodeError)
        text = "".join(c for c in text if ord(c) <= 255)
        
        return text.strip()
